config/routes.rb
Rails.application.routes.draw do 
  get 'oxoplastia/index'
  get 'store/index'
  root 'home#index'

  # Route for healthcheck
  get "/up/", to: "up#index", as: :up
  get "/up/databases", to: "up#databases", as: :up_databases

  # Rails Admin
  devise_for :users
  mount RailsAdmin::Engine => '/gestao-gov', as: 'rails_admin'

  post 'increment_quick_access_views/:id', to: 'application#increment_quick_access_views', as: :increment_quick_access_views

  #about
  get "sobre-nos", to: "about#index", as: :about 

  get "galeria-oxtoplastia", to: "gallery_ox#index", as: :gallery_ox 
  

  # Contact
  post 'fale-conosco' => 'contacts#create', as: :create_contact
  get 'fale-conosco' => 'contacts#index', as: :contact

  get "busca" => "searchs#index", as: :search

  # Uploader for ckeditor
  post '/post_images/upload/:model/:model_id' => 'post_images#upload'
  # Delete for ckeditor
  post '/post_images/delete/:post_image_id' => 'post_images#delete'

  # # Posts
  get "noticias/" => "posts#index", as: "posts"
  get "noticias/:slug" => "posts#show", as: "post"
  get "noticias/categoria/:category" => "posts#by_category", as: "posts_category"

  # # Album
  get "galerias" => "albums#index", as: :albums
  get "galerias/:slug" => "albums#show", as: :album

  get "galerias/:slug/adicionar-foto" => "albums#new_photo", as: :new_photo

  post "galerias/:slug/create_photo" => "albums#create_photo", as: :album_create_photo
 
  get 'category/:category', to: 'albums#category', as: 'category'


  #videos
  get "videos" => "videos#index", as: :videos
  get "video/:slug" => "videos#show", as: :video
 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  require 'open-uri'
  require 'nokogiri'
	include PostService

  def index
      @link_top = LinkTop.order(created_at: :desc).limit(5)
      @contact = Contact.new
      @banners = Banner.all 
      @about = About.first 
      @socials = SocialMedium.all
      @ox = Oxoplastium.all
      @gallery_ox = GalleryOx.all
      @config = Adjustment.first 
      @posts = Post.where("date_publish <= ? AND is_published = ?", Time.now, true).order(date_publish: "DESC")
      @featured_posts = Post.where(featured: true).order(date_publish: "DESC").limit(5)
      @non_featured_posts = Post.where(featured: false).order(date_publish: "DESC")
      @albuns = Album.where(featured: true).order(created_at: :desc).limit(4)
      @videos = Video.where(featured: true).order(created_at: :desc).limit(3)
      @schedule = ScheduleYourAppointment.all
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_about.html.erb
<% if @about.present? %>
  <section class="w-full hidden md:block bg-white" data-controller="scroll-active" data-scroll-active-target="section">
    <div class="container mx-auto py-20">
      <div class="flex flex-col md:flex-row justify-between items-center gap-10">
        <% if @about.photo.present? %>
          <div class="md:w-5/12 right-left-animation">
            <%= image_tag @about.photo_url, class: "w-full h-auto", style: "box-shadow: 2px 18px 18px #0E345E; border-radius: 20px;" %>
          </div>
        <% end %>
        <div class="md:w-7/12">
          <div class="mb-5 top-down-animation">
            <div class="">
              <h3 class="uppercase poppins-bold text-4xl text-zinc-600"><%= @about.sumary %></h3>
            </div>
          </div>
          <div class="">
            <div class="mb-10 left-right-animation">
              <span class="text-zinc-600 poppins-regular text-sm"><%= @about.text.html_safe %></span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
<% end %>

app/views/home/_album.html.erb
<% if @albuns.present? %>
  <section class="w-full">
    <div class="container mx-auto">
      <% @albuns.group_by { |album| album.album_category.name }.each do |category, albums| %>
        <div class="w-full mt-8">
          <div class="w-full flex justify-between items-center text-[<%= site_colors.primary %>] border-b-[2px] pb-[8px] mb-8 uppercase">
            <h2 class="text-md md:text-lg md:karla-bold uppercase"><%= category %></h2>
            <h5 class="text-md md:text-lg md:karla-bold">
              <%= link_to "Ver mais", category_path(category: category) %>
            </h5>
          </div>
          <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8">
            <% albums.each do |album| %>
              <div class="w-full h-40 relative rounded bg-slate-200 ">
                <%= link_to album_path(slug: album.slug), class: "block w-full h-full hover:scale-105 transition-all ease-in-out duration-300" do %>
                  <% if album.photos.any? %>
                    <%= image_tag album.photos.first.image_url, class: "w-full h-full object-cover rounded" %>
                  <% else %>
                    <%= image_tag "default_image.png", class: "w-full h-full object-cover rounded" %>
                  <% end %>
                  <div class="absolute z-10 bottom-0 p-2 md:p-4 bg-gradient-to-t from-[<%= site_colors.primary %>] rounded w-full">
                    <div class="text-white md:text-xl poppins-medium line-clamp-3"><%#= album.title %></div>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </section>
<% end %>

app/views/home/_banner.html.erb
<% featured_banners = banners_ads(1200, 500, 1, 3) %>

<% if featured_banners.present? %>
  <section class="relative exclude-contrast">
    <div data-controller="slide-banner" class="swiper group">
      <div class="w-full h-full swiper-wrapper">
        <% featured_banners.each do |featured_banner| %>
          <% if featured_banner.present? && featured_banner.photo.present? %>
            <div class="w-full h-full max-h-[500px] swiper-slide exclude-contrast">
              <div class="w-full h-full max-h-[500px] absolute flex flex-col z-30 justify-center px-8 exclude-contrast">
                <div class="container mx-auto flex flex-col items-center md:items-start gap-4 exclude-contrast">
                  <h2 class="hidden sm:block text-white text-md md:text-2xl md:karla-bold uppercase banner-subtitle exclude-contrast" style="font-family: <%= FontPrimary.first.category_font.title %>;">
                    <%= featured_banner.subtitle %>
                  </h2>
                  <% if featured_banner.link.present? %>
                    <h4>
                      <%= link_to featured_banner.link, class: "bg-[#{site_colors.primary}] px-4 md:px-8 py-2 md:py-4 w-fit text-white rounded font-semibold uppercase hover:scale-110 transition duration-300 banner-link exclude-contrast",  style:"font-family: #{FontSecondary.first.category_font.title};" do %>
                        Saiba Mais
                      <% end %>
                    </h4>
                  <% end %>
                </div>
              </div>
              <div class="bg-black opacity-30 group-hover:opacity-0 w-full h-full max-h-[500px] absolute exclude-contrast transition duration-300"></div>
              <%= image_tag featured_banner.photo_url, class: "h-full w-full max-h-[500px] object-cover exclude-contrast" %>
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="btn-next swiper-button-next bg-[<%= site_colors.primary %>] h-[32px] rounded p-4 mt-2 mx-4 opacity-0 group-hover:opacity-80 transition duration-300 exclude-contrast"></div>
      <div class="btn-prev swiper-button-prev bg-[<%= site_colors.primary %>] h-[32px] rounded p-4 mt-2 mx-4 opacity-0 group-hover:opacity-80 transition duration-300 exclude-contrast"></div>
    </div>
  </section>
<% end %>

<%# if featured_banners.present? %>
  <%# featured_banners.each do |featured_banner| %>
    <%# if featured_banner.present? && !featured_banner.photo.present? %>
      <%#= video_tag featured_banner.video_url, autoplay: true, loop: true, class: "h-full w-full max-h-[500px] object-cover exclude-contrast" %>
    <%# end %>
  <%# end %>
<%# end %>

<style>
  .swiper-button-next:after, .swiper-button-prev:after {
    font-size: 18px;
    color: #e0e0e0;
  }
</style>

app/views/home/_cookies.html.erb
<!-- Cookie Consent by TermsFeed https://www.TermsFeed.com -->
<script type="text/javascript" src="//www.termsfeed.com/public/cookie-consent/4.0.0/cookie-consent.js" charset="UTF-8"></script>
<script type="text/javascript" charset="UTF-8">
document.addEventListener('DOMContentLoaded', function () {
  cookieconsent.run({
    "notice_banner_type": "interstitial",
    "consent_type": "express",
    "palette": "light",
    "language": "pt",
    "page_load_consent_levels": ["strictly-necessary"],
    "notice_banner_reject_button_hide": false,
    "preferences_center_close_button_hide": false,
    "page_refresh_confirmation_buttons": false,
    "website_name": "Prefeitura de jateí"
  });

  // // Function to modify the styles of the cookie consent overlay
  // function modifyCookieConsentOverlay() {
  //   var overlay = document.querySelector('.termsfeed-com---nb-interstitial-overlay');
  //   if (overlay) {
  //     overlay.style.top = '';
  //     overlay.style.bottom = '0';
  //   }
  // }

  // Function to change the text of the element with ID 'cc-nb-text'
  function changeConsentText() {
    var consentText = document.getElementById('cc-nb-text');
    if (consentText) {
      consentText.innerHTML = 'Este site usa cookies para garantir que você tenha a melhor experiência em nosso site.';
    }
  }

  // Wait for a short time to ensure the cookie consent script has applied the initial styles and text
  setTimeout(function() {
    // modifyCookieConsentOverlay();
    changeConsentText();
  }, 0);
});
</script>
<noscript>Free cookie consent management tool by
  <a href="https://www.termsfeed.com/" rel="nofollow noopener">TermsFeed Policy Generator</a></noscript>


<!-- End Cookie Consent by TermsFeed https://www.TermsFeed.com --> <!-- Below is the link that users can use to open Preferences Center to change their preferences. Do not modify
the ID parameter. Place it where appropriate, style it as needed. -->


<style>
  
  .termsfeed-com---palette-light .cc-nb-okagree {
    background-color: <%= site_colors.primary %>;
  }
  .termsfeed-com---palette-light .cc-nb-reject {
    background-color: <%= site_colors.primary %>;
  }
  
</style>

app/views/home/_insta_show.html.erb
<div class="container mx-auto" style="margin-top: 100px;"> 
    <% @socials.each do |social| %>
      <% if social.insta_show.present? %>
        <div>
          <p class="text-map text-center" style="color: <%= site_colors.primary %>; font-family: <%= FontPrimary.first.category_font.title %>;">ACOMPANHE AS NOVIDADES PELO NOSSO INSTA:</p>
        </div>
        <%= social.insta_show.html_safe %>
      <% end %>
    <% end %> 
</div>

app/views/home/_location.html.erb
<div class="text-center" style="margin-top: 100px;">
  <p
    class="text-map"
    style="color: <%= site_colors.primary %>; font-family: <%= FontPrimary.first.category_font.title %>; position: relative; display: inline-block; margin-bottom: 30px;"
  >
    ESTAMOS LOCALIZADAS BEM AQUI:
    <span style="position: absolute; bottom: 0px; left: 0; right: 0; height: 1px; background-color: #0E345E;"></span>
  </p>
</div>

<div class="section__services-categories mb-5">
  <div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab" tabindex="0">
      <iframe
        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3692.671513506114!2d-53.35592366177851!3d-22.252538820137676!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x948e7d1b4e4a6c7f%3A0xc5faac0d322866c1!2sR.%20Walter%20Hubacher%2C%201848%20-%20Centro%2C%20Nova%20Andradina%20-%20MS%2C%2079750-000!5e0!3m2!1spt-BR!2sbr!4v1731353554943!5m2!1spt-BR!2sbr"
        style="width: 100%; height: 240px; border: 0;"
        allowfullscreen=""
        loading="lazy"
        referrerpolicy="no-referrer-when-downgrade"
      ></iframe>
    </div>
  </div>
</div>

app/views/home/_news.html.erb
<!-- filepath: /home/lari/Documentos/projetos-pessoais/milaine-beauty/app/views/home/_news.html.erb -->
<% if @posts.present? && @featured_posts.present? %>
  <section class="w-full py-12">
    <div class="container mx-auto">
      <div class="w-full flex justify-between text-[<%= site_colors.primary %>] border-b-[2px] pb-[8px] mb-8 uppercase">
        <h2 class="text-md md:text-lg md:karla-bold uppercase">Notícias</h2>
      </div>
      <div class="w-full h-[345px] sm:h-[500px] flex flex-col md:flex-row gap-4 md:gap-8">
        <!-- Slider de destaques -->
        <div data-controller="slide-news" class="swiper w-full md:w-3/5 rounded hover:scale-105 transition duration-300 group">
          <div class="swiper-wrapper">
            <% @featured_posts.first(3).each do |post| %>
              <div class="swiper-slide">
                <%= link_to post_path(post.slug), class: "block w-full h-full" do %>
                  <div class="w-full h-full relative rounded bg-slate-200">
                    <%= image_tag post.cover_url, class: "w-full h-full object-cover rounded" %>
                    <div class="absolute z-10 bottom-0 p-4 md:p-8 bg-gradient-to-t from-[<%= site_colors.primary %>] rounded w-full">
                      <div class="text-white md:text-2xl line-clamp-3" style="font-family: <%= FontPrimary.first.category_font.title %>;"><%= post.title %></div>
                    </div>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
          <!-- Paginação -->
          <div class="swiper-pagination exclude-contrast"></div>
          <!-- Navegação -->
          <div class="btn-next exclude-contrast swiper-button-next bg-[<%= site_colors.primary %>] h-[32px] rounded p-4 mt-2 mx-4 opacity-0 group-hover:opacity-80 transition duration-300 exclude-contrast"></div>
          <div class="btn-prev exclude-contrast swiper-button-prev bg-[<%= site_colors.primary %>] h-[32px] rounded p-4 mt-2 mx-4 opacity-0 group-hover:opacity-80 transition duration-300 exclude-contrast"></div>
        </div>
        <!-- Últimos dois posts destacados -->
        <div class="w-full md:w-2/5 h-32 md:h-auto exclude-contrast grid grid-cols-2 md:grid-cols-1 grid-rows-1 md:grid-rows-2 gap-4 md:gap-8">
          <% @featured_posts.last(2).each do |post| %>
            <div class="w-full h-full relative rounded bg-slate-200">
              <%= link_to post_path(post.slug), class: "block w-full h-full" do %>
                <%= image_tag post.cover_url, class: "w-full h-full object-cover rounded" %>
                <div class="absolute z-10 bottom-0 p-2 md:p-4 bg-gradient-to-t from-[<%= site_colors.primary %>] rounded w-full">
                  <div class="text-white md:text-xl line-clamp-3" style="font-family: <%= FontPrimary.first.category_font.title %>;"><%= post.title %></div>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </section>
<% end %>
<style>
  /* Estilo para todas as bolinhas de paginação */
  .swiper-pagination-bullet {
    background: #E6E6E6; /* Cor das bolinhas inativas */
    opacity: 1;
  }

  /* Estilo para a bolinha de paginação ativa */
  .swiper-pagination-bullet-active {
    background: <%= site_colors.terciary %>; /* Cor da bolinha ativa */
  }

  .swiper-button-next:after, .swiper-button-prev:after {
    padding: 3px 8px;
    color: white;
  }

  .swiper-button-next {
    right: 8px;
  }

  .swiper-button-prev, .swiper-rtl .swiper-button-next {
    left: auto;
    right: 41px;
  }

  .swiper-button-next, .swiper-button-prev {
    top: 5%;
  }
</style>

app/views/home/_news_non_featured.html.erb
<% if @non_featured_posts.present? %>
  <section class="w-full py-8">
    <div class="container mx-auto">
      <div class="w-full mt-8">
        <div class="w-full flex justify-between items-center text-[<%= site_colors.primary %>] border-b-[2px] pb-[8px] mb-8 uppercase">
          <h2 class="text-md md:text-lg uppercase"  style="font-family: <%= FontPrimary.first.category_font.title %>;">Ultimas Notícias</h2>
          <h5 class="text-md md:text-lg" style="font-family: <%= FontPrimary.first.category_font.title %>;">
            <%= link_to "Ver mais", posts_path %>
          </h5>
        </div>
        <div class="flex flex-col sm:flex-row lg:flex-col gap-4 h-full">
          <% @non_featured_posts.first(3).each do |post| %>
            <%= link_to post_path(post.slug), class: "lg:h-fit min-h-60 group transition-all ease-in-out duration-300 flex flex-col lg:flex-row w-full overflow-hidden lg:max-h-80 lg:gap-4 py-4 border-b" do %>
              <%= image_tag post.cover.url, class: "w-full h-auto object-cover rounded group-hover:scale-105 transition-all ease-in-out duration-300 drop-shadow-md lg:w-1/4 border" %>

              <div class="flex flex-col justify-between py-4 lg:py-0 lg:px-4 lg:w-3/4  text-[]<%= site_colors.terciary %> gap-2" style="font-family: <%= FontPrimary.first.category_font.title %>;">
                <div class="flex flex-col gap-3">
                  <div class="text-sm font-semibold capitalize">
                    <span class="text-[<%= site_colors.primary %>]">
                      <%= post.post_category.name %>
                    </span>
                    <span class="text-[<%= site_colors.terciary %>]">
                      /
                    </span>
                    <span class="text-sm w-full font-semibold"><%= post.formatted_date_publish %></span>
                  </div>
                  <div class="text-2xl font-semibold transition-all duration-300 ease-in-out group-hover:text-[<%= site_colors.primary %>] line-clamp-1"><%= post.title %></div>
                  <% if post.summary.present? %>
                    <p class="text-md line-clamp-3 text-[<%= site_colors.terciary %>]">
                      <%= truncate(post.summary, length: 320) %><br>
                    </p>
                  <% end %>
                </div>
                <div class="w-fit bg-[<%= site_colors.primary %>] px-12 py-1 text-white rounded hover:scale-110 transition-all ease-in-out duration-300">Ver</div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </section>
<% end %>

app/views/home/_oxtoplatia.html.erb
<div class="container mx-auto p-4">
  <% if @ox.present? %>
    <h1 class="text-3xl font-bold mb-2 text-center">Oxtoplatia</h1>
    <div class="mx-auto w-16 h-1 bg-blue-500 mb-4"></div>
    <div class="space-y-4">
      <% @ox.each do |ox| %>
        <div class="flex items-start space-x-4">
          <% if ox.photo.present? %>
            <div class="relative">
              <%= image_tag ox.photo_url, class: "w-[220px] h-[290px] object-cover rounded-lg border-2 border-transparent" %>
              <div class="absolute top-0 left-0 w-full h-full rounded-lg border-4 border-blue-500 blur-sm"></div>
            </div>
          <% end %>
          <div class="flex-1 mt-12">
            <p><%= ox.text %></p>
          </div>
        </div>
      <% end %>
    </div>
  <% end %> 

  <% if @gallery_ox.present? %>
    <div class="flex flex-wrap space-x-4">
      <% @gallery_ox.each do |photo| %>
        <div class="relative mb-4">
          <%= image_tag photo.photo.url, class: "w-[90px] h-[100px] object-cover rounded-lg border-2 border-transparent" %>
          <div class="absolute top-0 left-0 w-full h-full rounded-lg border-4 border-blue-500 blur-sm"></div>
        </div>
      <% end %>
    </div>
  <% end %>
  <div class="mt-6">
     <%= link_to "Galeria Oxtoplastia", gallery_ox_path, class: "bg-blue-500 text-white px-4 py-2 rounded-lg hover:bg-blue-700" %>
  </div>
</div>

app/views/home/_schedule_your_appointment.html.erb
<!-- filepath: /home/lari/Documentos/projetos-pessoais/milaine-beauty/app/views/home/_schedule_your_appointment.html.erb -->
<% @schedule.each do |schedule| %>
  <div class="max-w-3xl mx-auto my-5 bg-white rounded-lg shadow-md">
    <div class="flex flex-col md:flex-row items-center">
      <div class="w-full md:w-1/2">
        <%= image_tag schedule.photo_url, class: "w-full h-auto object-cover rounded-t-lg md:rounded-l-lg md:rounded-t-none" %>
      </div>
      <div class="w-full md:w-1/2 p-5 flex flex-col gap-5">
        <div class="text-2xl font-bold text-gray-800">
          <%= schedule.description %>
        </div>
        <div>
          <%= button_to "Agende seu horário", 
              "https://wa.me/#{format_phone_number(schedule.number)}", 
              method: :get, 
              target: "_blank",
              class: "bg-blue-900 text-white py-3 px-6 rounded-lg font-semibold w-full hover:bg-blue-700 transition-colors" 
          %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/home/_video.html.erb
<% if @videos.present? %>
  <section class="w-full pb-6">
    <div class="container mx-auto">
      <div class="w-full mt-8">
        <div class="w-full flex justify-between text-[<%= site_colors.primary %>] border-b-[2px] pb-[8px] mb-8 uppercase">
          <h2 class="text-md md:text-lg md:karla-bold uppercase">Vídeos</h2>
          <h5 class="text-md md:text-lg md:karla-bold">
            <%= link_to "Ver mais", videos_path %>
          </h5>
        </div>
        <div class="grid grid-cols-2 md:grid-cols-3 gap-8">
          <% @videos.each do |video| %>
            <div class="w-full h-52 relative rounded bg-slate-200 overflow-hidden group">
              <%= link_to video_path(slug: video.slug), class: "block w-full h-full absolute top-0 left-0 z-20" do %>
                <span class="sr-only"><%= video.title %></span>
              <% end %>
              <div class="relative h-full group-hover:scale-105 transition-all ease-in-out duration-300">
                <iframe class="w-full h-full" src="https://www.youtube.com/embed/<%= video.code %>" allowfullscreen></iframe>
              </div>
              <div class="absolute z-10 bottom-0 bg-gradient-to-t from-[<%= site_colors.primary %>] rounded w-full transition-all ease-in-out duration-300">
                <div class="text-white md:text-xl p-2 md:p-4 w-full poppins-medium"><%= video.title %></div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </section>
<% end %>

app/views/home/index.html.erb
<%= render "banner" %>
<%= render "about" %>
<%= render "news" %>
<%= render "news_non_featured" %>
<%= render "album" %>
<%= render "oxtoplatia" %>
<%= render "video" %>
<%= render "insta_show" %>

<%= render "location" %>
<%= render "schedule_your_appointment" %> 
<%= render "cookies" %>